spring:
  jpa.properties.hibernate.default_schema: jobservice
  jpa.hibernate.ddl-auto: none
  datasource:
    url: ${cloud.services.postgresql.connection.jdbcurl}
    driverClassName: org.postgresql.Driver
    continue-on-error: false
    schema: classpath:/schema-cloud.sql
    username: ${cloud.services.postgresql.connection.username}
    password: ${cloud.services.postgresql.connection.password}

liquibase:
  user: ${cloud.services.postgresql.connection.username}
  password: ${cloud.services.postgresql.connection.password}
  default-schema: jobservice
  url: ${cloud.services.postgresql.connection.jdbcurl}
  changeLog: classpath:db/changelog/db.changelog-master.yml

